from typing_extensions import TypeAlias, Literal
from typing import Annotated
from types import FunctionType
from uuid import UUID


# ranged int types are not regulated

uint8: TypeAlias = int  # 0 | 255
int8: TypeAlias = int # - 128 | 127

RGBvalue: TypeAlias = Annotated[tuple[uint8], 3]
screen_unit: TypeAlias = int | float
coordinate: TypeAlias = tuple[screen_unit, screen_unit]
generic_var: TypeAlias = str | None

fonts: TypeAlias = Literal[
    'arial', 'arialblack', 'bahnschrift', 'calibri', 'cambria', 'cambriamath', 'candara', 'comicsansms', 'consolas', 'constantia', 'corbel', 'couriernew', 'ebrima', 'franklingothicmedium', 'gabriola', 'gadugi', 'georgia', 'impact', 'inkfree', 'javanesetext', 'leelawadeeui', 'leelawadeeuisemilight', 'lucidaconsole', 'lucidasans', 'malgungothic', 'malgungothicsemilight', 'microsofthimalaya', 'microsoftjhenghei', 'microsoftjhengheiui', 'microsoftnewtailue', 'microsoftphagspa', 'microsoftsansserif', 'microsofttaile', 'microsoftyahei', 'microsoftyaheiui', 'microsoftyibaiti', 'mingliuextb', 'pmingliuextb', 'mingliuhkscsextb', 'mongolianbaiti', 'msgothic', 'msuigothic', 'mspgothic', 'mvboli', 'myanmartext', 'nirmalaui', 'nirmalauisemilight', 'palatinolinotype', 'segoemdl2assets', 'segoeprint', 'segoescript', 'segoeui', 'segoeuiblack', 'segoeuiemoji', 'segoeuihistoric', 'segoeuisemibold', 'segoeuisemilight', 'segoeuisymbol', 'simsun', 'nsimsun', 'simsunextb', 'sitkasmall', 'sitkatext', 'sitkasubheading', 'sitkaheading', 'sitkadisplay', 'sitkabanner', 'sylfaen', 'symbol', 'tahoma', 'timesnewroman', 'trebuchetms', 'verdana', 'webdings', 'wingdings', 'yugothic', 'yugothicuisemibold', 'yugothicui', 'yugothicmedium', 'yugothicuiregular', 'yugothicregular', 'yugothicuisemilight', 'holomdl2assets', 'agencyfbvet', 'agencyfb', 'algerian',
    'bookantiquavet', 'bookantiquavetcursief', 'bookantiquacursief', 'arialvet', 'arialvetcursief', 'arialcursief', 'arialrounded', 'baskervilleoldface', 'bauhaus93', 'bell', 'bellvet', 'bellcursief', 'bernardcondensed', 'bookantiqua', 'bodonivet', 'bodonivetcursief', 'bodoniblackcursief', 'bodoniblack', 'bodonicondensedvet', 'bodonicondensedvetcursief', 'bodonicondensedcursief', 'bodonicondensed', 'bodonicursief', 'bodonipostercompressed', 'bodoni', 'bookmanoldstyle', 'bookmanoldstylevet', 'bookmanoldstylevetcursief', 'bookmanoldstylecursief', 'bradleyhanditc', 'britannic', 'berlinsansfbvet', 'berlinsansfbdemivet', 'berlinsansfb', 'broadway', 'brushscriptcursief', 'bookshelfsymbol7', 'californianfbvet', 'californianfbcursief', 'californianfb', 'calisto', 'calistovet', 'calistovetcursief', 'calistocursief', 'castellar', 'centuryschoolbook', 'centaur', 'century', 'chiller', 'colonna', 'cooperblack', 'copperplategothic', 'curlz', 'dubai', 'dubaimedium', 'dubairegular', 'elephant', 'elephantcursief', 'engravers', 'erasitc', 'erasdemiitc', 'erasmediumitc', 'felixtitling', 'forte', 'franklingothicbook', 'franklingothicbookcursief', 'franklingothicdemi', 'franklingothicdemicond', 'franklingothicdemicursief', 'franklingothicheavy', 'franklingothicheavycursief', 'franklingothicmediumcond', 'freestylescript', 'frenchscript', 'footlight', 'garamond', 'garamondvet', 'garamondcursief', 'gigi', 'gillsansvetcursief', 'gillsansvet', 'gillsanscondensed', 'gillsanscursief', 'gillsansultracondensed', 'gillsansultra', 'gillsans', 'gloucesterextracondensed', 'gillsansextcondensed', 'centurygothic', 'centurygothicvet', 'centurygothicvetcursief', 'centurygothiccursief', 'goudyoldstyle', 'goudyoldstylevet', 'goudyoldstylecursief', 'goudystout', 'harlowsolid', 'harrington', 'haettenschweiler', 'hightowertext', 'hightowertextcursief', 'imprintshadow', 'informalroman', 'blackadderitc', 'edwardianscriptitc', 'kristenitc', 'jokerman',
    'juiceitc', 'kunstlerscript', 'widelatin', 'lucidabright', 'lucidacalligraphy', 'leelawadee', 'leelawadeevet', 'lucidafax', 'lucidafaxhalfvet', 'lucidafaxhalfvetcursief', 'lucidafaxcursief', 'lucidahandwritingcursief', 'lucidasanshalfvet', 'lucidasanshalfvetcursief', 'lucidasanscursief', 'lucidasanstypewriter', 'lucidasanstypewritervet', 'lucidasanstypewritervetschuin', 'lucidasanstypewriterschuin', 'magnetovet', 'maiandragd', 'maturascriptcapitals', 'mistral', 'modernno20', 'microsoftuighurvet', 'microsoftuighur', 'monotypecorsiva', 'extra', 'niagaraengraved', 'niagarasolid', 'ocraextended', 'oldenglishtext', 'onyx', 'msoutlook', 'palacescript', 'papyrus', 'parchment', 'perpetuavetcursief', 'perpetuavet', 'perpetuacursief', 'perpetuatitlingvet', 'perpetuatitlingmager', 'perpetua', 'playbill', 'poorrichard', 'pristina', 'rage', 'ravie', 'msreferencesansserif', 'msreferencespecialty', 'rockwellcondensedvet', 'rockwellcondensed', 'rockwell', 'rockwellvet', 'rockwellvetcursief', 'rockwellextra', 'rockwellcursief', 'centuryschoolbookvet', 'centuryschoolbookvetcursief', 'centuryschoolbookcursief', 'script', 'showcardgothic', 'snapitc', 'stencil', 'twcenvetcursief', 'twcenvet', 'twcencondensedvet', 'twcencondensedextra', 'twcencondensed', 'twcencursief', 'twcen', 'tempussansitc', 'vinerhanditc', 'vivaldicursief', 'vladimirscript', 'wingdings2', 'wingdings3', 'ti83emukeys', 'ti83emufrenchkeys', 'ti84emukeys', 'siemenstiaportalbasic', 'siemenslogo', 'xoumegs57condensedregular', 'siemensslabsc', 'siemensslab', 'siemenssans', 'siemenssanssc', 'winccflexible', 'siemensserif', 'siemensslabblack', 'siemensserifsemibold', 'siemensserifscsemi', 'siemensserifsc', 'siemenssansscblack', 'winccflexiblehigh', 'siemensslabscblack', 'siemensadsansregular', 'timesnewromanmathdot', 'kcmiges', 'ts3d', 'y145m2009', 'y145m', 'winccdigital', 'winccdigital1', 'winccdigital2', 'siemenssansbold', 'siemenssansblack', 'roboto', 'robotomedium', 'robotothin', 'zillaslab', 'githubocticons', 'octicons', 'menloregular', 'notosans', 'fontawesome', 'fontawesomeregular', 'teraspecial'
]

path: TypeAlias = str
# globalFont: TypeAlias = pygame.font.Font
functionAdress: TypeAlias = FunctionType
g_id: TypeAlias = UUID