from enum import IntEnum

class eventType(IntEnum):
    # Unused (do not remove)
    EVENT_FIRST = 0

    # Application events
    EVENT_QUIT = 0x100
    EVENT_TERMINATING = 0x101
    EVENT_LOW_MEMORY = 0x102
    EVENT_WILL_ENTER_BACKGROUND = 0x103
    EVENT_DID_ENTER_BACKGROUND = 0x104
    EVENT_WILL_ENTER_FOREGROUND = 0x105
    EVENT_DID_ENTER_FOREGROUND = 0x106
    EVENT_LOCALE_CHANGED = 0x107
    EVENT_SYSTEM_THEME_CHANGED = 0x108

    # Display events
    EVENT_DISPLAY_ORIENTATION = 0x151
    EVENT_DISPLAY_ADDED = 0x152
    EVENT_DISPLAY_REMOVED = 0x153
    EVENT_DISPLAY_MOVED = 0x154
    EVENT_DISPLAY_DESKTOP_MODE_CHANGED = 0x155
    EVENT_DISPLAY_CURRENT_MODE_CHANGED = 0x156
    EVENT_DISPLAY_CONTENT_SCALE_CHANGED = 0x157
    EVENT_DISPLAY_FIRST = EVENT_DISPLAY_ORIENTATION
    EVENT_DISPLAY_LAST = EVENT_DISPLAY_CONTENT_SCALE_CHANGED

    # Window events
    EVENT_WINDOW_SHOWN = 0x202
    EVENT_WINDOW_HIDDEN = 0x203
    EVENT_WINDOW_EXPOSED = 0x204
    EVENT_WINDOW_MOVED = 0x205
    EVENT_WINDOW_RESIZED = 0x206
    EVENT_WINDOW_PIXEL_SIZE_CHANGED = 0x207
    EVENT_WINDOW_METAL_VIEW_RESIZED = 0x208
    EVENT_WINDOW_MINIMIZED = 0x209
    EVENT_WINDOW_MAXIMIZED = 0x20A
    EVENT_WINDOW_RESTORED = 0x20B
    EVENT_WINDOW_MOUSE_ENTER = 0x20C
    EVENT_WINDOW_MOUSE_LEAVE = 0x20D
    EVENT_WINDOW_FOCUS_GAINED = 0x20E
    EVENT_WINDOW_FOCUS_LOST = 0x20F
    EVENT_WINDOW_CLOSE_REQUESTED = 0x210
    EVENT_WINDOW_HIT_TEST = 0x211
    EVENT_WINDOW_ICCPROF_CHANGED = 0x212
    EVENT_WINDOW_DISPLAY_CHANGED = 0x213
    EVENT_WINDOW_DISPLAY_SCALE_CHANGED = 0x214
    EVENT_WINDOW_SAFE_AREA_CHANGED = 0x215
    EVENT_WINDOW_OCCLUDED = 0x216
    EVENT_WINDOW_ENTER_FULLSCREEN = 0x217
    EVENT_WINDOW_LEAVE_FULLSCREEN = 0x218
    EVENT_WINDOW_DESTROYED = 0x219
    EVENT_WINDOW_HDR_STATE_CHANGED = 0x21A
    EVENT_WINDOW_FIRST = EVENT_WINDOW_SHOWN
    EVENT_WINDOW_LAST = EVENT_WINDOW_HDR_STATE_CHANGED

    # Keyboard events
    EVENT_KEY_DOWN = 0x300
    EVENT_KEY_UP = 0x301
    EVENT_TEXT_EDITING = 0x302
    EVENT_TEXT_INPUT = 0x303
    EVENT_KEYMAP_CHANGED = 0x304
    EVENT_KEYBOARD_ADDED = 0x305
    EVENT_KEYBOARD_REMOVED = 0x306
    EVENT_TEXT_EDITING_CANDIDATES = 0x307

    # Mouse events
    EVENT_MOUSE_MOTION = 0x400
    EVENT_MOUSE_BUTTON_DOWN = 0x401
    EVENT_MOUSE_BUTTON_UP = 0x402
    EVENT_MOUSE_WHEEL = 0x403
    EVENT_MOUSE_ADDED = 0x404
    EVENT_MOUSE_REMOVED = 0x405

    # Joystick events
    EVENT_JOYSTICK_AXIS_MOTION = 0x600
    EVENT_JOYSTICK_BALL_MOTION = 0x601
    EVENT_JOYSTICK_HAT_MOTION = 0x602
    EVENT_JOYSTICK_BUTTON_DOWN = 0x603
    EVENT_JOYSTICK_BUTTON_UP = 0x604
    EVENT_JOYSTICK_ADDED = 0x605
    EVENT_JOYSTICK_REMOVED = 0x606
    EVENT_JOYSTICK_BATTERY_UPDATED = 0x607
    EVENT_JOYSTICK_UPDATE_COMPLETE = 0x608

    # Gamepad events
    EVENT_GAMEPAD_AXIS_MOTION = 0x650
    EVENT_GAMEPAD_BUTTON_DOWN = 0x651
    EVENT_GAMEPAD_BUTTON_UP = 0x652
    EVENT_GAMEPAD_ADDED = 0x653
    EVENT_GAMEPAD_REMOVED = 0x654
    EVENT_GAMEPAD_REMAPPED = 0x655
    EVENT_GAMEPAD_TOUCHPAD_DOWN = 0x656
    EVENT_GAMEPAD_TOUCHPAD_MOTION = 0x657
    EVENT_GAMEPAD_TOUCHPAD_UP = 0x658
    EVENT_GAMEPAD_SENSOR_UPDATE = 0x659
    EVENT_GAMEPAD_UPDATE_COMPLETE = 0x65A
    EVENT_GAMEPAD_STEAM_HANDLE_UPDATED = 0x65B

    # Touch events
    EVENT_FINGER_DOWN = 0x700
    EVENT_FINGER_UP = 0x701
    EVENT_FINGER_MOTION = 0x702
    EVENT_FINGER_CANCELED = 0x703

    # Clipboard events
    EVENT_CLIPBOARD_UPDATE = 0x900

    # Drag and drop events
    EVENT_DROP_FILE = 0x1000
    EVENT_DROP_TEXT = 0x1001
    EVENT_DROP_BEGIN = 0x1002
    EVENT_DROP_COMPLETE = 0x1003
    EVENT_DROP_POSITION = 0x1004

    # Audio hotplug events
    EVENT_AUDIO_DEVICE_ADDED = 0x1100
    EVENT_AUDIO_DEVICE_REMOVED = 0x1101
    EVENT_AUDIO_DEVICE_FORMAT_CHANGED = 0x1102

    # Sensor events
    EVENT_SENSOR_UPDATE = 0x1200

    # Pressure-sensitive pen events
    EVENT_PEN_PROXIMITY_IN = 0x1300
    EVENT_PEN_PROXIMITY_OUT = 0x1301
    EVENT_PEN_DOWN = 0x1302
    EVENT_PEN_UP = 0x1303
    EVENT_PEN_BUTTON_DOWN = 0x1304
    EVENT_PEN_BUTTON_UP = 0x1305
    EVENT_PEN_MOTION = 0x1306
    EVENT_PEN_AXIS = 0x1307

    # Camera hotplug events
    EVENT_CAMERA_DEVICE_ADDED = 0x1400
    EVENT_CAMERA_DEVICE_REMOVED = 0x1401
    EVENT_CAMERA_DEVICE_APPROVED = 0x1402
    EVENT_CAMERA_DEVICE_DENIED = 0x1403

    # Render events
    EVENT_RENDER_TARGETS_RESET = 0x2000
    EVENT_RENDER_DEVICE_RESET = 0x2001
    EVENT_RENDER_DEVICE_LOST = 0x2002

    # Reserved events for private platforms
    EVENT_PRIVATE0 = 0x4000
    EVENT_PRIVATE1 = 0x4001
    EVENT_PRIVATE2 = 0x4002
    EVENT_PRIVATE3 = 0x4003

    # Internal events
    EVENT_POLL_SENTINEL = 0x7F00

    # User events
    EVENT_USER = 0x8000

    # Last event (for bounding internal arrays)
    EVENT_LAST = 0xFFFF

    # Padding to ensure enum size
    EVENT_ENUM_PADDING = 0x7FFFFFFF